// src/components/RVs.tsx
import localforage from "localforage";
import { Component, For, createSignal } from "solid-js";
import Card from "./Card";
import type { RV } from "./utils";

const RVs: Component = () => {
  const [RVArray, setRVArray] = createSignal<RV[]>([]);
  localforage.keys().then((keys) => {
    keys.forEach((key) => {
      localforage.getItem(key).then((value) => {
        setRVArray([...RVArray(), value] as RV[]);
      });
    });
  });
  return (
    <div class="flex flex-col gap-5">
      <For each={RVArray()}>{(RV) => <Card RV={RV} />}</For>
    </div>
  );
};

export default RVs;

// src/components/RVs.svelte
<script lang="ts">
  import localforage from "localforage";
  import Card from "./Card.svelte";
  import type { RVType } from "./utils";

  let RVArray: RVType[] = [];
  localforage.keys().then((keys) => {
    keys.forEach((key) => {
      localforage.getItem(key).then((value) => {
        RVArray = [...RVArray, value] as RVType[];
      });
    });
  });
</script>

<div class="flex flex-col gap-5">
  {#each RVArray as RV}
    <Card {RV} />
  {/each}
</div>
